In [1]:
import numpy as np

In [3]:
Sx = np.array([[0.0, 1.0],
               [1.0, 0.0]])
eigenvalue_x, eigenvector_x = np.linalg.eig(Sx)
eigenvalue_x, eigenvector_x

(array([ 1., -1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [4]:
Sy = np.array([[0.0, -1.0j],
               [1.0j, 0.0]])
eigenvalue_y, eigenvector_y = np.linalg.eig(Sy)
eigenvalue_y, eigenvector_y

(array([ 1.+0.j, -1.+0.j]),
 array([[-0.        -0.70710678j,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.        -0.70710678j]]))

In [5]:
Sz = np.array([[1.0, 0.0],
              [0.0, -1.0]])
eigenvalue_z, eigenvector_z = np.linalg.eig(Sz)
eigenvalue_z, eigenvector_z

(array([ 1., -1.]),
 array([[1., 0.],
        [0., 1.]]))

In [6]:
coef_mat = np.array([[2.0, -1.0],
                     [-1.0, 2.0]])
eigenvalue_coef_mat, eigenvector_coef_mat = np.linalg.eig(coef_mat)
eigenvalue_coef_mat, eigenvector_coef_mat

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

아이겐벨류는 (3,1), 아이겐벡터는 (0.70710678,0.70710678)이 나왔는데,

$\lambda$값을 대입해 $x_1$과 $x_2$의 비율인 아이겐벡터를 계산하여 물체의 노말모드를 관찰할 수 있다.

아이겐벨류($\lambda$)가 1일 때에는 $x_1$값과$x_2$값이 같기 때문에 두 물체가 똑같이 운동하는 걸 관찰할 수 있고,

아이겐벨류($\lambda$)가 3일 때에는 $x_1$값과$x_2$값이 부호가 반대여서 같은 크기로 운동을 하지만 방향이 반대라는 것을 관찰할 수 있다.

$w_1$은 한쪽이 최대값을 가질 때 다른 쪽은 최솟값을 갖는 위상각이 180도 다르고 같은 속도 반대방향으로 운동하고,

$w_2$는 위상,속도,방향이 모두 같다.


아이겐벡터를 쪼갤 수 있기 때문에 계의 모든 진동을 고유벡터, 고유값과 관련 된 normal mode들로 선형결합하여 표현할 수 있다.